# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

def even_fibonacci_sum(max)
  
 # create array for fib numbers < 4,000,000 
 fib = [] 

 # generate array
  i1, i2 = 1, 2
  while i1 <= max
    fib.push(i1)
    i1, i2 = i2, i1+i2
  end

  # iterate through array, adding only even values
  sum = 0
  fib.each do |x|
    if x.even?
      sum += x
    end 
  end

  return sum
  # sum = 4,613,735

end

even_fibonacci_sum(4000000)



